const NotificationTypes = Object.freeze({
    POST: 'POST',
    MESSAGE: 'MESSAGE',
    FRIEND_REQUEST: 'FRIEND_REQUEST',
    MENTION: 'MENTION',
    FOLLOW: 'FOLLOW',
    COMMENT: 'COMMENT',
    POST_REACTION: 'POST_REACTION',
    TEAM_INVITE: 'TEAM_INVITE',
    TEAM_INVITE_ACCEPTED: 'TEAM_INVITE_ACCEPTED',
    CONTEST_REVIEW_ACCEPTED: 'CONTEST_REVIEW_ACCEPTED',
    CONTEST_UNDER_REVIEW: 'CONTEST_UNDER_REVIEW',
    CONTEST_SUBMITTED_FOR_REVIEW: 'CONTEST_SUBMITTED_FOR_REVIEW',
    PLAN_SUBMITTED_FOR_REVIEW: 'PLAN_SUBMITTED_FOR_REVIEW'
  })
  module.exports = NotificationTypes;